### ISSUE TITLE
Adding some CI

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#7] opened 2021-11-02 12:24 UTC
- [ ] Install Flake8
- [ ] Add GitHub actions configuration

**Comment by AvivLiberman** [comment] 2021-11-03 21:08
@avraham_chababo Can you take care of it?

**Comment by avraham1992** [comment] 2021-11-03 21:53
Do not know what the problem is he tells me he does not recognize the command .. all files exist I sat on it tomorrow at noon again

**Comment by orzionpour** [comment] 2021-11-04 20:08
https://github.com/redhat-beyond/falcon/pull/12

**Comment by orzionpour** [comment] 2021-11-07 07:50
Resolved in #15

**Closed** 2021-11-07 09:14 UTC
